language: node_js
sudo: required
node_js:
- "4"
before_install:
- npm install -g codecov
- npm install -g typescript
- npm install -g typings
- npm install -g istanbul
script:
- npm test
after_success:
  - codecov